// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef BRAKE_H
#define BRAKE_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

class Brake_Config;

class Brake: public Subsystem, public Configurable {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	int    PCMID;
	int    Channel;
	bool   ActiveIsEngaged;
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Solenoid> brakeSolenoid;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Brake();
	virtual ~Brake();
	virtual void RetrieveConfig();
	virtual void Configure();
	virtual void SaveConfig();
	virtual void CreateConfig();

    void InitDefaultCommand();
    void Engage();
    void Release();
    bool IsEngaged();


};

#endif
