#ifndef DRIVETRAINCONFIG_H
#define DRIVETRAINCONFIG_H

class DriveTrain_Config
{
public:
	float  DriveTrain_HighSpeed;
	float  DriveTrain_LowSpeed;
	float  DriveTrain_QuadEncoder_PulsesPerDegree;
	bool   DriveTrain_RightTalon1_Enabled;
	int    DriveTrain_RightTalon1_CANID;
	bool   DriveTrain_RightTalon1_Reversed;
	bool   DriveTrain_RightTalon1_HasSensor;
	bool   DriveTrain_RightTalon1_SensorReversed;
	bool   DriveTrain_RightTalon1_EnablePID;
	double DriveTrain_RightTalon1_Profile_0_PID_P;
	double DriveTrain_RightTalon1_Profile_0_PID_I;
	double DriveTrain_RightTalon1_Profile_0_PID_D;
	double DriveTrain_RightTalon1_Profile_0_PID_F;
	int    DriveTrain_RightTalon1_Profile_0_IZone;
	bool   DriveTrain_RightTalon1_Profile_0_EnableCLRampRate;
	double DriveTrain_RightTalon1_Profile_0_CLRampRate;
	double DriveTrain_RightTalon1_Profile_1_PID_P;
	double DriveTrain_RightTalon1_Profile_1_PID_I;
	double DriveTrain_RightTalon1_Profile_1_PID_D;
	double DriveTrain_RightTalon1_Profile_1_PID_F;
	int    DriveTrain_RightTalon1_Profile_1_IZone;
	bool   DriveTrain_RightTalon1_Profile_1_EnableCLRampRate;
	double DriveTrain_RightTalon1_Profile_1_CLRampRate;
	bool   DriveTrain_RightTalon1_EnableVoltRampRate;
	double DriveTrain_RightTalon1_VoltRampRate;
	float  DriveTrain_RightTalon1_QuadEncoder_PulsesPerInch;
	int    DriveTrain_RightTalon1_PID_CL_PM_Error;
	bool   DriveTrain_RightTalon1_Slaved;
	int    DriveTrain_RightTalon1_MasterCANID;

	bool   DriveTrain_RightTalon2_Enabled;
	int    DriveTrain_RightTalon2_CANID;
	bool   DriveTrain_RightTalon2_Reversed;
	bool   DriveTrain_RightTalon2_HasSensor;
	bool   DriveTrain_RightTalon2_SensorReversed;
	bool   DriveTrain_RightTalon2_EnablePID;
	double DriveTrain_RightTalon2_Profile_0_PID_P;
	double DriveTrain_RightTalon2_Profile_0_PID_I;
	double DriveTrain_RightTalon2_Profile_0_PID_D;
	double DriveTrain_RightTalon2_Profile_0_PID_F;
	int    DriveTrain_RightTalon2_Profile_0_IZone;
	bool   DriveTrain_RightTalon2_Profile_0_EnableCLRampRate;
	double DriveTrain_RightTalon2_Profile_0_CLRampRate;
	double DriveTrain_RightTalon2_Profile_1_PID_P;
	double DriveTrain_RightTalon2_Profile_1_PID_I;
	double DriveTrain_RightTalon2_Profile_1_PID_D;
	double DriveTrain_RightTalon2_Profile_1_PID_F;
	int    DriveTrain_RightTalon2_Profile_1_IZone;
	bool   DriveTrain_RightTalon2_Profile_1_EnableCLRampRate;
	double DriveTrain_RightTalon2_Profile_1_CLRampRate;
	bool   DriveTrain_RightTalon2_EnableVoltRampRate;
	double DriveTrain_RightTalon2_VoltRampRate;
	float  DriveTrain_RightTalon2_QuadEncoder_PulsesPerInch;
	int    DriveTrain_RightTalon2_PID_CL_PM_Error;
	bool   DriveTrain_RightTalon2_Slaved;
	int    DriveTrain_RightTalon2_MasterCANID;

	bool   DriveTrain_LeftTalon1_Enabled;
	int    DriveTrain_LeftTalon1_CANID;
	bool   DriveTrain_LeftTalon1_Reversed;
	bool   DriveTrain_LeftTalon1_HasSensor;
	bool   DriveTrain_LeftTalon1_SensorReversed;
	bool   DriveTrain_LeftTalon1_EnablePID;
	double DriveTrain_LeftTalon1_Profile_0_PID_P;
	double DriveTrain_LeftTalon1_Profile_0_PID_I;
	double DriveTrain_LeftTalon1_Profile_0_PID_D;
	double DriveTrain_LeftTalon1_Profile_0_PID_F;
	int    DriveTrain_LeftTalon1_Profile_0_IZone;
	bool   DriveTrain_LeftTalon1_Profile_0_EnableCLRampRate;
	double DriveTrain_LeftTalon1_Profile_0_CLRampRate;
	double DriveTrain_LeftTalon1_Profile_1_PID_P;
	double DriveTrain_LeftTalon1_Profile_1_PID_I;
	double DriveTrain_LeftTalon1_Profile_1_PID_D;
	double DriveTrain_LeftTalon1_Profile_1_PID_F;
	int    DriveTrain_LeftTalon1_Profile_1_IZone;
	bool   DriveTrain_LeftTalon1_Profile_1_EnableCLRampRate;
	double DriveTrain_LeftTalon1_Profile_1_CLRampRate;
	bool   DriveTrain_LeftTalon1_EnableVoltRampRate;
	double DriveTrain_LeftTalon1_VoltRampRate;
	float  DriveTrain_LeftTalon1_QuadEncoder_PulsesPerInch;
	int    DriveTrain_LeftTalon1_PID_CL_PM_Error;
	bool   DriveTrain_LeftTalon1_Slaved;
	int    DriveTrain_LeftTalon1_MasterCANID;

	bool   DriveTrain_LeftTalon2_Enabled;
	int    DriveTrain_LeftTalon2_CANID;
	bool   DriveTrain_LeftTalon2_Reversed;
	bool   DriveTrain_LeftTalon2_HasSensor;
	bool   DriveTrain_LeftTalon2_SensorReversed;
	bool   DriveTrain_LeftTalon2_EnablePID;
	double DriveTrain_LeftTalon2_Profile_0_PID_P;
	double DriveTrain_LeftTalon2_Profile_0_PID_I;
	double DriveTrain_LeftTalon2_Profile_0_PID_D;
	double DriveTrain_LeftTalon2_Profile_0_PID_F;
	int    DriveTrain_LeftTalon2_Profile_0_IZone;
	bool   DriveTrain_LeftTalon2_Profile_0_EnableCLRampRate;
	double DriveTrain_LeftTalon2_Profile_0_CLRampRate;
	double DriveTrain_LeftTalon2_Profile_1_PID_P;
	double DriveTrain_LeftTalon2_Profile_1_PID_I;
	double DriveTrain_LeftTalon2_Profile_1_PID_D;
	double DriveTrain_LeftTalon2_Profile_1_PID_F;
	int    DriveTrain_LeftTalon2_Profile_1_IZone;
	bool   DriveTrain_LeftTalon2_Profile_1_EnableCLRampRate;
	double DriveTrain_LeftTalon2_Profile_1_CLRampRate;
	bool   DriveTrain_LeftTalon2_EnableVoltRampRate;
	double DriveTrain_LeftTalon2_VoltRampRate;
	float  DriveTrain_LeftTalon2_QuadEncoder_PulsesPerInch;
	int    DriveTrain_LeftTalon2_PID_CL_PM_Error;
	bool   DriveTrain_LeftTalon2_Slaved;
	int    DriveTrain_LeftTalon2_MasterCANID;

};

#endif
