// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Pivot_Stick.h"


Pivot_Stick::Pivot_Stick(): Command() {
	Requires(Robot::intake.get());
	obsCount = 0;
}


// Called just before this Command runs the first time
void Pivot_Stick::Initialize() {
	obsCount = 0;
}

// Called repeatedly when this Command is scheduled to run
void Pivot_Stick::Execute() {
	axisState = Robot::oi->getOperatorInterface()->Get_AxisState();

	if (axisState.DPAD != -1)
	{
		if (obsCount == 0)
		{
			if (axisState.DPAD == 0)
			{
				Robot::intake->UpPivot();
				obsCount = axisState.AxisDelay;
			}
			if (axisState.DPAD == 180)
			{
				Robot::intake->DownPivot();
				obsCount = axisState.AxisDelay;
			}
		} else
		{
			obsCount--;
		}
	} else
	{
		obsCount--;
	}
	if (obsCount < 0 )
		{
			SmartDashboard::PutNumber("PivotIndex", RobotMap::pivotEncoder->Get());
			obsCount = 0;
		}
}

// Make this return true when this Command no longer needs to run execute()
bool Pivot_Stick::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void Pivot_Stick::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Pivot_Stick::Interrupted() {

}
