// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Fire.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Fire::Fire(int cycles): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooter.get());
	Requires(Robot::intake.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	count = cycles;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Fire::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void Fire::Execute() {
	Robot::shooter->Fire1();
	if (Robot::shooter->AtRPM())
	{
		if (Robot::dresselIR->IsInRange())
		{
			count--;
			printf("Fire: Count %d\n",count);
		}
		Robot::intake->SetIntake(true);
	}
}

// Make this return true when this Command no longer needs to run execute()
bool Fire::IsFinished() {
    if (count == 0) return true;
    return false;
}

// Called once after isFinished returns true
void Fire::End() {
	Robot::shooter->Stop();
	Robot::intake->StopIntake();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Fire::Interrupted() {

}
