// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/Intake_In.h"
#include "Commands/Intake_Out.h"
#include "Commands/ScaleSequence.h"
#include "Commands/TargetAssist_Active.h"
#include "Commands/Teleop_Drive.h"
#include "Commands/Toggle_Compressor.h"
#include "Commands/Toggle_TargettingAssist.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.

	driverInterface.reset(new XBOX360_Controller("Driver",0));
    
	operatorInterface.reset(new XBOX360_Controller("Operator",1));
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    // SmartDashboard Buttons
    SmartDashboard::PutData("ScaleSequence", new ScaleSequence());
    SmartDashboard::PutData("Toggle_TargettingAssist", new Toggle_TargettingAssist());
    SmartDashboard::PutData("TargetAssist_Active", new TargetAssist_Active());
    SmartDashboard::PutData("Toggle_Compressor", new Toggle_Compressor());
    SmartDashboard::PutData("Intake_Out", new Intake_Out());
    SmartDashboard::PutData("Intake_In", new Intake_In());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    //operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_B, new ExtendCanBurgler(),ButtonAction::ButtonAction_Pressed);
    //operatorInterface->Assign_ButtonCommand(XBOX360_BUTTON::XBOX360_B, new RetractCanBurgler(),ButtonAction::ButtonAction_Released);

}


std::shared_ptr<XBOX360_Controller> OI::getDriverInterface(){
   return driverInterface;
}

std::shared_ptr<XBOX360_Controller> OI::getOperatorInterface(){
   return operatorInterface;
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
