// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"
#include "Xbox360_Controller.h"

class OI : public Configurable {
private:
	std::shared_ptr<XBOX360_Controller> driverInterface;
	std::shared_ptr<XBOX360_Controller> operatorInterface;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	int cycles;
public:
	OI();
	virtual ~OI();
	std::shared_ptr<XBOX360_Controller> getDriverInterface();
	std::shared_ptr<XBOX360_Controller> getOperatorInterface();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	virtual void RetrieveConfig();
	virtual void Configure();
	virtual void SaveConfig();
	virtual void LiveConfigure();
};

#endif
