// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef _ROBOT_H
#define _ROBOT_H

#include "WPILib.h"
#include "Commands/Command.h"
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
#include "Robot_Config.h"
#include "Logger.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Commands/AutonomousCommand.h"
#include "Commands/Autonomous_Simple.h"
#include "Subsystems/DriveTrain.h"
#include "Subsystems/Intake.h"
#include "Subsystems/Pivot.h"
#include "Subsystems/PDP.h"
#include "Subsystems/Pneumatics.h"
#include "Subsystems/Scaler.h"
#include "Subsystems/Shooter.h"
#include "Subsystems/Sensors.h"
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "Subsystems/Stabilizer.h"


#include "OI.h"
#include "SmartDashboard/SmartDashboard.h"
#include "SmartDashboard/SendableChooser.h"

#include "Commands/Sensor_Output.h"
#include "Video.h"


class Robot : public IterativeRobot {
public:
	static std::unique_ptr<Robot_Config> theConfig;
	static std::unique_ptr<Logger> theLogger;
	static std::unique_ptr<Command> autonomousCommand;
	static std::unique_ptr<Command> autonomous_simple;
	static std::unique_ptr<Command> sensorOut;
	static std::unique_ptr<OI> oi;
	LiveWindow *lw = LiveWindow::GetInstance();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static std::shared_ptr<DriveTrain> driveTrain;
    static std::shared_ptr<Pneumatics> pneumatics;
    static std::shared_ptr<Intake> intake;
    static std::shared_ptr<Pivot> pivot;
    static std::shared_ptr<Scaler> scaler;
    static std::shared_ptr<PDP> pDP;
    static std::shared_ptr<Shooter> shooter;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    static std::shared_ptr<Stabilizer> stabilizer;
    static std::shared_ptr<Sensors> sensorPkg;
    static std::shared_ptr<Video> videoSys;

    virtual void RobotInit();
	virtual void DisabledInit();
	virtual void DisabledPeriodic();
	virtual void AutonomousInit();
	virtual void AutonomousPeriodic();
	virtual void TeleopInit();
	virtual void TeleopPeriodic();
	virtual void TestInit();
	virtual void TestPeriodic();
private:

};
#endif
