// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef VIDEO_H
#define VIDEO_H
#include "WPILib.h"
#include "Robot_Config.h"
#include "Xbox360_Controller.h"
#include "USBCamera.h"

class Video{
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	bool   FrontActive;
	bool   FrontInit;
	bool   BackInit;
	VideoCfg *myConfig;
	XBOX360_Controller *myController;
	int currentUpdate;

/*	IMAQdxSession Front;
	IMAQdxSession Back;
	IMAQdxSession current;*/
	Image *frame;
	CameraServer *server;
	std::shared_ptr<USBCamera> frontCam;
	std::shared_ptr<USBCamera> rearCam;

public:
	Video();
    bool Init(VideoCfg *config,XBOX360_Controller *controller);
    void Run();
    void End();
    void LiveConfigure();
    void ProcessStream();
    void ToggleView();
    void SelectFront();
    bool IsFrontSelected();
    void SelectRear();
    bool IsRearSelected();


};

#endif
