// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef SCALER_H
#define SCALER_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Scaler: public Subsystem , public Configurable {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
	std::shared_ptr<Solenoid> scalerStage1;
	std::shared_ptr<Solenoid> scalerStage2;

	int  PCMID;
	int  scalarStage1Channel;
	int  scalarStage2Channel;
	bool stage1ActiveIsExtended;
	bool stage2ActiveIsExtended;

public:
	Scaler();
	virtual ~Scaler();
	void InitDefaultCommand();

	virtual void RetrieveConfig();
	virtual void Configure();
	virtual void SaveConfig();
	virtual void LiveConfigure();

	void Stage1Extend();
	void Stage1Retract();
	bool IsStage1Extended();

	void Stage2Extend();
	void Stage2Retract();
	bool IsStage2Extended();

};

#endif
