// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Sensors.h"
#include "../RobotMap.h"



Sensors::Sensors() : Subsystem("Sensors"), Configurable("Sensors") {
	printf("Sensors Start\n");
    IR_Front.reset( new IR_Sensor(RobotMap::sensorIRdSensorFront, "IR_Sensor::Front"));
    IR_Shooter.reset( new IR_Sensor(RobotMap::sensorIRdSensor, "IR_Sensor::Shooter"));
    IR_Tower.reset(new IR_Sensor(RobotMap::sensorIRdSensorTower, "IR_Sensor::Tower"));
    pressure = RobotMap::pressureSensor;
    _pDp = RobotMap::pDPPowerDistributionPanel;
    imu.reset(new IMU());

    TowerInRangeRumble = 0;

	CheckConfig("Tower::InRangeRumble");
	Configure();
}
    
Sensors::~Sensors()
{

}

void Sensors::RetrieveConfig()
{
	IR_Front->RetrieveConfig();
	IR_Shooter->RetrieveConfig();
	IR_Tower->RetrieveConfig();
	imu->RetrieveConfig();
	TowerInRangeRumble = Preferences::GetInstance()->GetFloat(_prefix + prefSep + "Tower::InRangeRumble",0.0);
}

void Sensors::SaveConfig()
{
	IR_Front->SaveConfig();
	IR_Shooter->SaveConfig();
	IR_Tower->SaveConfig();
	imu->SaveConfig();
	Preferences::GetInstance()->PutFloat(_prefix + prefSep + "Tower::InRangeRumble",TowerInRangeRumble);
}

void Sensors::Configure()
{
	IR_Front->Configure();
	IR_Shooter->Configure();
	IR_Tower->Configure();
	imu->Configure();
}

void Sensors::LiveConfigure()
{
	RetrieveConfig();
	IR_Front->LiveConfigure();
	IR_Shooter->LiveConfigure();
	IR_Tower->LiveConfigure();
	imu->LiveConfigure();
}


void Sensors::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
}

float Sensors::GetTowerInRangeRumble()
{
	return TowerInRangeRumble;
}

bool Sensors::RobotHasBall()
{
	if (IR_Front->IsInRange())
	{
		return true;
	}
	return false;
}

bool Sensors::IsBallAtShooter()
{
	if (IR_Shooter->IsInRange())
	{
		return true;
	}
	return false;
}

bool Sensors::TowerInRange()
{
	if (IR_Tower->IsInRange())
	{
		return true;
	}
	return false;
}

float Sensors::GetAirPressure()
{
	float vout = pressure->GetVoltage();
	return (250.0 *(vout/5.0) - 25.0);
}

bool Sensors::IsPivotAtHome()
{
	return false;
}

bool Sensors::IsPivotAtIntake()
{
	return false;
}

bool Sensors::IsPivotAtLow()
{
	return false;
}

void Sensors::SetFrontIn()
{
	IR_Front->SetIn();
}

void Sensors::SetFrontOut()
{
	IR_Front->SetOut();
}

void Sensors::SetShooterIn()
{
	IR_Shooter->SetIn();
}

void Sensors::SetShooterOut()
{
	IR_Shooter->SetOut();
}

void Sensors::StoreCalibration()
{
	IR_Front->StoreCalibration();
	IR_Shooter->StoreCalibration();
}
