// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef Stabilizer_H
#define Stabilizer_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"

class Stabilizer: public Subsystem, public Configurable {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	int    PCMID;
	int    FwdChannel;
	int    RevChannel;
	bool   ForwardIsDeployed;
	std::shared_ptr<DoubleSolenoid> StabilizerSolenoid;

public:
	Stabilizer();
	virtual ~Stabilizer();
	virtual void RetrieveConfig();
	virtual void Configure();
	virtual void SaveConfig();
	virtual void LiveConfigure();

    void InitDefaultCommand();
    void Deploy();
    void Retract();
    bool IsDeployed();
};

#endif
