// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "Stabilizer.h"
#include "../RobotMap.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES


Stabilizer::Stabilizer() : Subsystem("Stabilizer"), Configurable("Stabilizer") {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	Stabilizer = RobotMap::stabilizerSolenoid;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ActiveIsDeployed = true;

	if (!ConfigExists()) CreateConfig();

    RetrieveConfig();
	Configure();
}
    
Stabilizer::~Stabilizer()
{

}

void Stabilizer::RetrieveConfig()
{
	PCMID = Preferences::GetInstance()->GetInt("Stabilizer::PCMID",0);
	Channel = Preferences::GetInstance()->GetInt("Stabilizer::Channel",5);
	ActiveIsDeployed = Preferences::GetInstance()->GetBoolean("Stabilizer::ActiveIsDeployed",false);
}

void Stabilizer::SaveConfig()
{
	Preferences::GetInstance()->PutInt("Stabilizer::PCMID",PCMID);
	Preferences::GetInstance()->PutInt("Stabilizer::Channel",Channel);
	Preferences::GetInstance()->PutBoolean("Stabilizer::ActiveIsDeployed",ActiveIsDeployed);
}

void Stabilizer::Configure()
{
	// Do Nothing.
}

void Stabilizer::CreateConfig()
{
	Preferences::GetInstance()->PutInt("Stabilizer::PCMID",0);
	Preferences::GetInstance()->PutInt("Stabilizer::Channel",5);
	Preferences::GetInstance()->PutBoolean("Stabilizer::ActiveIsDeployed",false);
}


void Stabilizer::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.
void Stabilizer::Deploy()
{
	StabilizerSolenoid->Set(ActiveIsDeployed);
}

void Stabilizer::Retract()
{
	StabilizerSolenoid->Set(!ActiveIsDeployed);
}

bool Stabilizer::IsDeployed()
{
	bool retval = StabilizerSolenoid->Get();

	if ((ActiveIsDeployed && retval) || (!ActiveIsDeployed && !retval))
	{
		return true;
	}
	return false;
}
