// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef VIDEO_H
#define VIDEO_H
#include "Commands/Subsystem.h"
#include "WPILib.h"
#include "../Configurable.h"


class Video: public Subsystem, public Configurable {
private:
	// It's desirable that everything possible under private except
	// for methods that implement subsystem capabilities
	float  FrontQuality;
	float  RearQuality;

	int    FrontSize;
	int    RearSize;

	bool   FrontEnable;
	bool   RearEnable;

	bool   FrontActive;

	std::string FrontName;
	std::string RearName;

	std::shared_ptr<USBCamera> front;
	std::shared_ptr<USBCamera> rear;

public:
	Video();
	virtual ~Video();
	virtual void RetrieveConfig();
	virtual void Configure();
	virtual void SaveConfig();
	virtual void LiveConfigure();

    void InitDefaultCommand();

    void ToggleView();
    void SelectFront();
    bool IsFrontSelected();
    void SelectRear();
    bool IsRearSelected();
};

#endif
