// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Cal_Shooter_In.h"
#include "../RobotMap.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Cal_Shooter_In::Cal_Shooter_In(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
	printf("Cal_Shooter_In begin\n");
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::sensorPkg.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    printf("Cal_Shooter_In end\n");
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Cal_Shooter_In::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void Cal_Shooter_In::Execute() {
	//Robot::intake->sensors->SetShooterIn();
}

// Make this return true when this Command no longer needs to run execute()
bool Cal_Shooter_In::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void Cal_Shooter_In::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Cal_Shooter_In::Interrupted() {

}
