// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Disable_Shooter.h"
#include "../RobotMap.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Disable_Shooter::Disable_Shooter(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
	Requires(Robot::sensorPkg.get());
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Disable_Shooter::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void Disable_Shooter::Execute() {
	bool over = Robot::sensorPkg->Is_ShooterOveridden();
	Robot::sensorPkg->Set_ShooterOveride(!over);
}

// Make this return true when this Command no longer needs to run execute()
bool Disable_Shooter::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void Disable_Shooter::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Disable_Shooter::Interrupted() {

}
