// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Drive_Straight.h"

Drive_Straight::Drive_Straight(float inches): Command() {
	Requires(Robot::driveTrain.get());
	target = inches;
}
// Called just before this Command runs the first time
void Drive_Straight::Initialize() {
	Robot::driveTrain->Enable_Auto_Mode();
	Robot::driveTrain->AutoDrive_SetYawLock(true);
}

// Called repeatedly when this Command is scheduled to run
void Drive_Straight::Execute() {
	Robot::driveTrain->AutoDrive_SetDistance(target);
}

// Make this return true when this Command no longer needs to run execute()
bool Drive_Straight::IsFinished() {
    return Robot::driveTrain->AtCommandedPosition();
}

// Called once after isFinished returns true
void Drive_Straight::End() {
	Robot::driveTrain->AutoDrive_SetYawLock(false);
	Robot::driveTrain->Disable_Auto_Mode();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Drive_Straight::Interrupted() {

}
