// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Intake_SlowOut.h"

Intake_SlowOut::Intake_SlowOut(): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
	Requires(Robot::intake.get());
	TimeOut = 0.0;
}
// Called just before this Command runs the first time
void Intake_SlowOut::Initialize() {
	TimeOut = Robot::theConfig->_IntakeCfg.SlowOut_Timeout;

	// Set the timeout.
	SetTimeout(TimeOut);
}

// Called repeatedly when this Command is scheduled to run
void Intake_SlowOut::Execute() {
	Robot::intake->SetIntake(false,Robot::theConfig->_IntakeCfg.SlowOutSpeed);
}

// Make this return true when this Command no longer needs to run execute()
bool Intake_SlowOut::IsFinished() {
	if (IsTimedOut()) return true;
    return false;
}

// Called once after isFinished returns true
void Intake_SlowOut::End() {
	Robot::intake->StopIntake();
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Intake_SlowOut::Interrupted() {
	End();
}
