// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include <Commands/ScalerStage2.h>
#include "../RobotMap.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

ScalerStage2::ScalerStage2(bool override): Command() {
        // Use requires() here to declare subsystem dependencies
    // eg. requires(chassis);
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::scaler.get());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	_override = override;
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void ScalerStage2::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void ScalerStage2::Execute() {
	if (Robot::scaler->IsStage2Extended() && !_override)
	{
		Robot::scaler->Stage2Retract();
	} else
	{
		Robot::scaler->Stage2Extend();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool ScalerStage2::IsFinished() {
    return false;
}

// Called once after isFinished returns true
void ScalerStage2::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ScalerStage2::Interrupted() {

}
