#ifndef SENSOR_OUTPUT_H
#define SENSOR_OUTPUT_H

#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class Sensor_Output: public Command {
public:
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	Sensor_Output();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

private:
	int count;
	bool hasBall;
	bool IsBallAtShooter;
	bool IsTowerInRange;
	float airp;
	bool isHome;
	bool isIntake;
	bool isLow;

};

#endif
