// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "Stabilizer_Deploy.h"
#include "../RobotMap.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

Stabilizer_Deploy::Stabilizer_Deploy(): Command() {
	Requires(Robot::stabilizer.get());
}
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

// Called just before this Command runs the first time
void Stabilizer_Deploy::Initialize() {
}

// Called repeatedly when this Command is scheduled to run
void Stabilizer_Deploy::Execute() {
	if (!Robot::stabilizer->IsDeployed()) {
		Robot::stabilizer->Deploy();
	}
}

// Make this return true when this Command no longer needs to run execute()
bool Stabilizer_Deploy::IsFinished() {
    return true;
}

// Called once after isFinished returns true
void Stabilizer_Deploy::End() {
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void Stabilizer_Deploy::Interrupted() {

}
